### ISSUE TITLE
Use rustls for reqwest

### ISSUE THREAD

**Issue by DirkRusche** [robertohuertasm/log-tracing-layer#5]
Hi, first of all, thanks for this library.

I'm wondering if you can create a feature flag so that rustls is used?

**Comment by robertohuertasm** [comment]
Good idea! Let me check it out.

**Comment by robertohuertasm** [comment]
@DirkRusche which of the crates are you interested in using? Datadog, New Relic?

**Comment by DirkRusche** [comment]
> @DirkRusche which of the crates are you interested in using? Datadog, New Relic?

Datadog

**Comment by robertohuertasm** [comment]
Hi @DirkRusche, a new v0.5.0 version has been published. Can you give it a try? The feature is called `tls`.  Let me know how it goes. 

Thanks for creating this issue! ❤️
